# Generated by Django 6.0.2 on 2026-02-21 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(verbose_name='ID del Juego (IGDB)')),
                ('estado', models.CharField(choices=[('JUGANDO', 'Jugando'), ('TERMINADO', 'Terminado'), ('ABANDONADO', 'Abandonado'), ('PENDIENTE', 'Pendiente (Backlog)')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('nota', models.IntegerField(blank=True, null=True, verbose_name='Nota (1-5)')),
                ('resena', models.TextField(blank=True, null=True, verbose_name='Reseña')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Juego',
                'verbose_name_plural': 'Registros de Juegos',
                'ordering': ['-fecha_modificacion'],
            },
        ),
    ]
